"""empty message

Revision ID: 1869eb1d2dff
Revises: e1b996dad079
Create Date: 2022-08-14 18:06:35.432567

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1869eb1d2dff'
down_revision = 'e1b996dad079'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('etudiants', sa.Column('adresse', sa.String(length=250), nullable=True))
    op.alter_column('etudiants', 'nom',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.alter_column('etudiants', 'prenom',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('etudiants', 'prenom',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.alter_column('etudiants', 'nom',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.drop_column('etudiants', 'adresse')
    # ### end Alembic commands ###
