"""empty message

Revision ID: 3f849269fb3d
Revises: bbc5b1e6a81d
Create Date: 2022-08-14 18:10:05.528402

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f849269fb3d'
down_revision = 'bbc5b1e6a81d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('etudiants', 'email')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('etudiants', sa.Column('email', sa.VARCHAR(length=250), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
