"""empty message

Revision ID: bbc5b1e6a81d
Revises: 1869eb1d2dff
Create Date: 2022-08-14 18:08:30.841664

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bbc5b1e6a81d'
down_revision = '1869eb1d2dff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('etudiants', sa.Column('email', sa.String(length=250), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('etudiants', 'email')
    # ### end Alembic commands ###
